# Generated by Django 3.1.1 on 2020-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camelapp', '0002_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='call',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
