# Generated by Django 3.1 on 2020-09-06 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camelapp', '0004_auto_20200906_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='date',
            new_name='upload',
        ),
    ]
